accounts/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)

app_name = 'accounts'

urlpatterns = [
    # Login
    path('login/', login_view, name='login'),
    # Logout
    path('logout', logout_view, name='logout'),
    # Registration form
    path('signup', signup_view, name='signup'),

    # Other URL patterns
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # path('login/', MyLoginView.as_view(redirect_authenticated_user=True), name='login'),
    # path('register/', RegisterView.as_view(), name='register'),
    # path('logout/', LogoutView.as_view(next_page='login'), name='logout'),

]

blog/urls.py
from django.urls import path

from blog.feed import LatestEntriesFeed
from blog.views import *

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path("rss/feed/", LatestEntriesFeed()),
    # path('test', test, name='test'),

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from django.urls import path

from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    re_path(r'^robots\.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            print(request.user.username + " is authenticated Sucessfully")
            return redirect('/')
            # Redirect to a success page
        else:
            messages.error(request, 'The User NotFound')
            # Return an 'invalid login' error message
            return HttpResponseRedirect(reverse('accounts:login'))
    else:
        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
        # Render the login form


def login_view_old(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = AuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    print(request.user.username + " is authenticated Sucessfully")
                    return redirect('/')
                else:
                    print(request.user.username + "  is NOT authenticated")

        form = AuthenticationForm()
        context = {'form': form}
        return render(request, 'accounts/login.html', context)
    else:
        return redirect('/')


@login_required(login_url='./login')
def logout_view(request):
    logout(request)
    return redirect('/')


from accounts.forms import SignUpForm


def signup_view(request):
    # test comments
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                raw_password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=raw_password)
                login(request, user)
                return redirect('/')
        else:
            # Get Method
            form = SignUpForm()
            context = {'form': form}
            return render(request, 'accounts/signup.html', context)
    else:
        return redirect('/')

templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Form | CodingLab</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
</head>
<body>
<div class="container">
    <div class="wrapper">
        <div class="title"><span>Login Form</span></div>
        <form action="{% url 'accounts:login' %}" method="post">
            {% csrf_token %}
            <div class="row">
                <i class="fas fa-user"></i>
                <input name="username" type="text" placeholder="Email or Username" required>
            </div>
            <div class="row">
                <i class="fas fa-lock"></i>
                <input name="password" type="password" placeholder="Password" required>
            </div>


            <div class="pass"><a href="{% url 'accounts:password_reset' %}">Forgot password?</a></div>
            <div class="row button">
                <input type="submit" value="Login">
            </div>
            <div class="signup-link">Not a member? <a href="{% url 'accounts:signup' %}">Signup now</a></div>
        </form>

            <div class="signup-link">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}

                    {% endfor %}
               {% endif %}

            </div>


    </div>
</div>

</body>
</html>

templates/accounts/login1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login Page</title>
</head>
<body>
<form method="post" action="{% url 'accounts:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" value="Click to send" > Click ME to Send</button>
</form>
</body>

</html>

templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>logout Page</h1>
</body>
</html>

templates/accounts/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>CodePen - Sign up / Login Form</title>
  <link rel="stylesheet" href="{% static 'css/stylesignup.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html>
<head>
	<title>Slide Navbar</title>
	<link rel="stylesheet" type="text/css" href="slide navbar style.css">
<link href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap" rel="stylesheet">
</head>
<body>
	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form method="post"action="{% url 'accounts:signup' %}">
                    {% csrf_token %}
					<label for="chk" aria-hidden="true">Sign up</label>
					<input type="text" name="username" placeholder="User name" required="">
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="password1" placeholder="Password" required="">
					<input type="password" name="password2" placeholder="Confirmed Password" required="">
					<button>Sign up</button>
				</form>
			</div>

{#			<div class="login">#}
{#				<form>#}
{#					<label for="chk" aria-hidden="true">Login</label>#}
{#					<input type="text" name="username" placeholder="Email" required="">#}
{#					<input type="password" name="password" placeholder="Password" required="">#}
{##}
{#					<button>Login</button>#}
{#				</form>#}
{#			</div>#}
	</div>
</body>
</html>
<!-- partial -->
  
</body>
</html>

templates/accounts/signupold.html
{% load static %}
<!doctype html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Login Page</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body> <!-- partial:index.partial.html -->

<section>
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span> <span></span>#}
    {#    <span></span> <span></span> <span></span> <span></span>#}

    <div class="signin">

        <div class="content">

            <h2>Sign Up</h2>

            <div class="form">
                <form method="post" action="{% url 'accounts:signup' %}">
                    {% csrf_token %}
                    <div class="inputBox">
                        <input name='username' type="text" required> <i>Username</i>
                    </div>
                    <br>
                    <div class="inputBox">
                        <input name='password1' type="password" required> <i>Password</i>
                        <input name='password2' type="password" required> <i>Confirm Password</i>
                    </div>



{#                                        {{ form.as_p }}#}


                    {#                    </div>#}
                    <br>
                    <div class="inputBox">

                        <input type="submit" value="SignUp">
                    </div>
                </form>

            </div>

        </div>

    </div>

</section> <!-- partial -->

</body>

</html>