blog/urls.py
from django.urls import path

from blog.feed import LatestEntriesFeed
from blog.views import *

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>', blog_single, name='single'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path("rss/feed/", LatestEntriesFeed()),
    # path('test', test, name='test'),

]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from django.urls import path

from blog.sitemaps import BlogSitemap
from website.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    'blog': BlogSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps},
         name="django.contrib.sitemaps.views.sitemap"),
    re_path(r'^robots\.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = models.ImageField(default='blog/defaults.jpg')
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_required = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} - {}'.format(self.title, self.id)

    class Meta:
        ordering = ["-created_date"]

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    create_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-create_date"]

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from blog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils import timezone
from blog.forms import CommentForm


# Create your views here.
# @login_required(login_url='../accounts/login')
def blog_view(request, **kwargs):
    #  Chapter 6 - Part 1 Excersice
    current_datetime = timezone.now()
    posts = Post.objects.filter(status=1, published_date__lte=current_datetime).order_by('-published_date')

    if kwargs.get('cat_name') is not None:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if kwargs.get('author_username') is not None:
        posts = posts.filter(author__username=kwargs['author_username'])
    if kwargs.get('tag_name') is not None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    try:
        posts = Paginator(posts, 3)
        page_number = request.GET.get("page")
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(posts.num_pages)

    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)


# Create your views here.
def blog_single(request, pid):
    if request.method == 'POST':

        form = CommentForm(request.POST)
        # form.instance.post_id = pid
        print(form.instance.post_id)
        if form.is_valid():
            form.save()
            messages.success(request, 'کامنت  شما با موفقیت ثبت شد.')
        else:
            messages.error(request, 'متاسفانه کامنت شما ثبت نشد.')

    try:
        current_datetime = timezone.now()
        #  Chapter 6 - Part 1 Excersice
        post = get_object_or_404(Post, id=pid, status=1, published_date__lte=current_datetime)
        if request.method == 'GET':
            post.counted_views += 1
            post.save()

        #  Chapter 6-Part 2 Excersice
        lst_post = list(
            Post.objects.filter(status=1, published_date__lte=current_datetime).order_by('-published_date'))
        post_index = lst_post.index(post)
        if post_index > 0:
            prev_post = lst_post[post_index - 1]
        else:
            prev_post = None

        if post_index == len(lst_post) - 1:
            next_post = None
        else:
            next_post = lst_post[post_index + 1]
        if post.login_required:
            if request.user.is_authenticated:
                comments = Comment.objects.filter(post=post.id, approved=True).order_by('-create_date')
                form = CommentForm()
                context = {'post': post, 'prev_post': prev_post, 'next_post': next_post, 'comments': comments,
                           'form': form}
                return render(request, 'blog/blog-single.html', context)
            else:
                return HttpResponseRedirect(reverse('accounts:login'))
        else:
            comments = Comment.objects.filter(post=post.id, approved=True).order_by('-create_date')
            form = CommentForm()
            context = {'post': post, 'prev_post': prev_post, 'next_post': next_post, 'comments': comments,
                       'form': form}
            return render(request, 'blog/blog-single.html', context)
    except Post.DoesNotExist:
        raise Http404("No MyModel matches the given query.")


def blog_category(request, cat_name):
    posts = Post.objects.filter(category__name=cat_name)

    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)


def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        if s := request.GET.get('s'):
            print()
            posts = posts.filter(content__contains=s)
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

# def test(request):
#     if request.method == 'POST':
#         name=request.POST.get('name')
#         email=request.POST.get('email')
#         subject=request.POST.get('subject')
#         message=request.POST.get('message')
#         print(name, email, subject, message)
#
#     return render(request, 'test.html')

templates/blog/blog-home.html
{% extends "base.html" %}
{% load static %}
{% load blog_tag %}
{% block content %}


    <!-- start banner Area -->
    <section class="banner-area relative blog-home-banner" id="home">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content blog-header-content col-lg-12">
                    <h1 class="text-white">
                        Dude You’re Getting
                        a Telescope
                    </h1>
                    <p class="text-white">
                        There is a moment in the life of any aspiring astronomer that it is time to buy that first
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start top-category-widget Area -->
    <section class="top-category-widget-area pt-90 pb-90 ">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="single-cat-widget">
                        <div class="content relative">
                            <div class="overlay overlay-bg"></div>
                            <a href="#" target="_blank">
                                <div class="thumb">
                                    <img class="content-image img-fluid d-block mx-auto"
                                         src="{% static 'img/blog/cat-widget1.jpg' %}" alt="">
                                </div>
                                <div class="content-details">
                                    <h4 class="content-title mx-auto text-uppercase">Social life</h4>
                                    <span></span>
                                    <p>Enjoy your social life together</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-cat-widget">
                        <div class="content relative">
                            <div class="overlay overlay-bg"></div>
                            <a href="#" target="_blank">
                                <div class="thumb">
                                    <img class="content-image img-fluid d-block mx-auto"
                                         src="{% static 'img/blog/cat-widget2.jpg' %}" alt="">
                                </div>
                                <div class="content-details">
                                    <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                                    <span></span>
                                    <p>Be a part of politics</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="single-cat-widget">
                        <div class="content relative">
                            <div class="overlay overlay-bg"></div>
                            <a href="#" target="_blank">
                                <div class="thumb">
                                    <img class="content-image img-fluid d-block mx-auto"
                                         src="{% static 'img/blog/cat-widget3.jpg' %}" alt="">
                                </div>
                                <div class="content-details">
                                    <h4 class="content-title mx-auto text-uppercase">Food</h4>
                                    <span></span>
                                    <p>Let the food be finished</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End top-category-widget Area -->

    <!-- Start post-content Area -->
    <section class="post-content-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    {% for post in posts %}
                        <div class="single-post row">
                            <div class="col-lg-3  col-md-3 meta-details">
                                <ul class="tags">

                                    {% for cat in post.category.all %}
                                        <a href="{% url 'blog:category' cat_name=cat.name %}">
                                            {{ cat.name }}
                                            {% if not forloop.last %}
                                                ,
                                            {% endif %}
                                        </a>
                                    {% endfor %}
                                </ul>
                                <div class="user-details row">
                                    <p class="user-name col-lg-12 col-md-12 col-6"><a
                                            href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author.get_full_name }}</a>
                                        <span
                                                class="lnr lnr-user"></span></p>
                                    <p class="date col-lg-12 col-md-12 col-6"><a
                                            href="#">{{ post.published_date | date:"d M Y" }}</a>
                                        <span class="lnr lnr-calendar-full"></span></p>
                                    <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_views }}
                                        Views</a> <span class="lnr lnr-eye"></span></p>
                                    <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{% comment_count  post.id%} Comments</a> <span
                                            class="lnr lnr-bubble"></span></p>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 ">
                                <div class="feature-img">

                                    <img class="img-fluid" src=" {{ post.image.url }}" alt="">
                                </div>
                                <a class="posts-title" href="{% url 'blog:single' pid=post.id %}">
                                    <h3>{{ post.title }}</h3></a>
                                <p class="excert">
                                    {#Chapter 6- Excersice 3#}
                                    {{ post.content| truncatewords:25 }}
                                </p>
                                <a href="{% url 'blog:single' pid=post.pk %}" class="primary-btn">View More</a>
                            </div>
                        </div>
                    {% endfor %}

                    <nav class="blog-pagination justify-content-center d-flex">
                        {#                        <div class="pagination">#}
                        {#                            <span class="step-links">#}
                        {#                                    {% if posts.has_previous %}#}
                        {##}
                        {#                                        <a href="?page={{ posts.previous_page_number }}">{{ posts.previous_page_number }}</a>#}
                        {#                                    {% endif %}#}
                        {##}
                        {#                                <span class="current"> {{ posts.number }} </span>#}
                        {##}
                        {#                                {% if posts.has_next %}#}
                        {#                                    <a href="?page={{ posts.next_page_number }}">{{ posts.next_page_number }}</a>#}
                        {#                                    <a href="?page={{ posts.paginator.num_pages }}">last &raquo;</a>#}
                        {#                                {% endif %}#}
                        {#                             </span>#}
                        {#                        </div>#}
                        <ul class="pagination">
                            <li class="page-item">
                                {% if posts.has_previous %}
                                    <a href="?page={{ posts.previous_page_number }}" class="page-link"
                                       aria-label="Previous">
                        		                                    <span aria-hidden="true">
                        		                                        <span class="lnr lnr-chevron-left"></span>
                        		                                    </span>
                                    </a>
                                {% endif %}
                            </li>
                            {% for i in posts.paginator.page_range %}
                                {% if  posts.number == i %}
                                    <li class="page-item active"><a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {#                            #}
                            {#                            <li class="page-item"><a href="#" class="page-link">03</a></li>#}
                            {#                            <li class="page-item"><a href="#" class="page-link">04</a></li>#}
                            {#                            <li class="page-item"><a href="#" class="page-link">09</a></li>#}
                            <li class="page-item">


                                {% if posts.has_next %}
                                    <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                        		                                    <span aria-hidden="true">
                        		                                        <span class="lnr lnr-chevron-right"></span>
                        		                                    </span>
                                    </a>
                                {% endif %}
                            </li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        {% include 'blog/blog-search.html' %}

                        {% include "blog/blog-writer.html" %}
                        {% latest_post_side %}

                        {% blog_post_categories %}
                        <div class="single-sidebar-widget ads-widget">
                            <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
                        </div>

                        <div class="single-sidebar-widget newsletter-widget">
                            <h4 class="newsletter-title">Newsletter</h4>
                            <p>
                                Here, I focus on a range of items and features that we use in life without
                                giving them a second thought.
                            </p>
                            <div class="form-group d-flex flex-row">
                                <div class="col-autos">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <div class="input-group-text"><i class="fa fa-envelope"
                                                                             aria-hidden="true"></i>
                                            </div>
                                        </div>
                                        <input type="text" class="form-control" id="inlineFormInputGroup"
                                               placeholder="Enter email" onfocus="this.placeholder = ''"
                                               onblur="this.placeholder = 'Enter email'">
                                    </div>
                                </div>
                                <a href="#" class="bbtns">Subcribe</a>
                            </div>
                            <p class="text-bottom">
                                You can unsubscribe at any time
                            </p>
                        </div>
{#                        {%  include 'blog-tags.html' %}#}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->

    "{% endblock content %}

templates/blog/blog-lastposts.html
{% load static %}
<div class="single-sidebar-widget popular-post-widget">

        <h4 class="popular-title">Popular Posts</h4>
    {% for post in posts %}
        <div class="popular-post-list">
            <div class="single-post-list d-flex flex-row align-items-center">
                <div class="thumb">
                    <img class="img-fluid " src="{{ post.image.url }}" alt="">
                </div>
                <div class="details">
                    {#Chapter 6- Excersice 3#}
                    <a href="{% url 'blog:single' pid=post.id %}"><h6>{{ post.title|truncatewords:5}}</h6></a>
                    <p>{{ post.published_date|date:'d M Y' }}</p>
                </div>
            </div>

        </div>
    {% endfor %}
</div>

templates/blog/blog-search.html
{% load static %}
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text"
               onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
                            <img src="{% static 'img/blog/user-info.png' %}" alt="">
                            <a href="#"><h4>Charlie Barber</h4></a>
                            <p>
                                Senior blog writer
                            </p>
                            <ul class="social-links">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-github"></i></a></li>
                                <li><a href="#"><i class="fa fa-behance"></i></a></li>

                            </ul>
                            <p>
                                Boot camps have its supporters andit sdetractors. Some people do not understand why you
                                should have to spend money on boot camp when you can get. Boot camps have itssuppor ters
                                andits detractors.
                            </p>
                        </div>

templates/blog/post-categories.html
{% load static %}

<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">

        {% for name,items in categories.items %}
        <li>

            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{ name }}</p>
                <p>{{ items }}</p>
            </a>
        </li>
    {% endfor %}
    </ul>
</div>